traviscross/mtr

mtr.8, mtr.c
It's been bugging me for a while that mtr always starts in stats mode, and lacks a command line switch to start in one of the stripchart modes, so I added the switch --displaymode, and included it in the man page and usage output. (This resolves issue #42 btw)
=> Added --displaymode option

configure.ac
This works for me on latest Solaris both with and without ncurses installed; I've done no testing on old versions or on other OSes.
=> Fix issue #76: rationalize the discovery of a terminal handling library

gtk.c
Now is timer added only when Pause button is not pressed.
=> Fixed behaviour of Pause button

display.c
Fixes a warning when compiling without ncurses being installed.
Warning was produced when running:
$ ./configure --without-gtk
$ make
display.c: In function ‘display_keyaction’:
display.c:169:5: warning: ‘return’ with no value, in function returning non-void [-Wreturn-type]
return mtr_curses_keyaction();
^
=> Remove a warning message at compile time.

curses.c
Properly use "-1" as terminal background color, when use_default_colors() succeeds.
Patch comes from, and closes #72.
=> curses: Fix background transparency in terminal

asn.h, report.c
There was a typo in csv_close() that prevented --csv from printing anything useful.
I also took the opportunity to add a csv header line to the printout, and changed every separator to a comma (rather than having the first entry be separated by semicolon.) These changes yield a csv file format that I personally find most convenient, in particular for post-processing by R. I hope they will be regarded as generally useful changes.
=> Fix and improvements for --csv 

net.c
As per http://stackoverflow.com/a/15881825 which references the manpage
ip(4) on *BSD and MacOSX:
"The ip_len and ip_off fields must be provided in host byte order.
All other fields must be provided in network byte order."
Before this commit, mtr would incorrectly set the length field of the UDP
header in host byte order after the first packet, as can be witnessed in
the following excerpt:
1st packet (TTL=1):
IP (tos 0x0, ttl 1, id 51530, offset 0, flags [none], proto UDP (17), length 64)
192.168.178.61.1143 > 8.8.8.8.33000: UDP, *** length 36 ***
IP (tos 0xc0, ttl 64, id 34040, offset 0, flags [none], proto ICMP (1), length 92)
192.168.178.1 > 192.168.178.61: ICMP time exceeded in-transit, length 72
IP (tos 0x0, ttl 1, id 51530, offset 0, flags [none], proto UDP (17), length 64) …
=> Fix setting length field of UDP header to broken value on BSD systems.

asn.c
Now that 32-bit ASNs are becoming more common the output of -z should take their width into consideration.
=> Update asn.c - 32bit ASN widths

net.c
The psize patch had only been applied in newdns.  I must have forgotten to patch master as well.
=> Correct psize for IPv6.

dns.c
Noticed a problem on Debian returning garbage names when the getnameinfo() return code was -3, but this is applicable to any OS regardless.
=> Need to error check getnameinfo().

Makefile.am
Per the security recommendations, when installing the binary, attempt to use setcap first and do setuid only if the setcap fails (usually because it doesn't exist).
=> Use setcap instead of setuid when installing the binary.

mtr.8, mtr.c, net.c
remove the MAX_UNKNOWN_HOSTS macro, use maxUnknown variable
instead of it, and add --max-unknown option, let it can be
configured at run time.
I hit the limit of MAX_UNKNOWN_HOSTS, my test path has 6 unknown host, So I should recompiled mtr and in crease the value of MAX_UNKNOWN_HOSTS. I hope mtr can support to adjust this value at run time.
=> add max-unknown option

display.c, display.h, mtr.8, mtr.c, report.c, report.h
This is based on the equivalent code for XML. It should produce valid JSON (with proper commas and everything). The new command line option is --json.
=> Add support for JSON as report output format

Makefile.am, asn.h, bootstrap.sh, configure.ac, curses.c, display.c, display.h, gtk.c, mtr.c, report.c, select.c, split.c
This pull request relates almost entirely to build system.  Change 262291a makes some of the oldest and most broken operating environments not to be able to compile this projec, but I doubt such systems would have worked earlier.
Secondly the pkg-config is made explicitly required. Again some users on some ancient systems may be upset about this, but IMHO the pkg-config, portable and future proved way to find dependencies in uniformed expected manner. And it is not even that controversial anymore - see https://en.wikipedia.org/wiki/GNU_Build_System#Components that has pkg-config listed along side with make, gettext, and gcc.
=> Pkg config

net.c
Mantas Mikulenas reviewed recent pull reques that contained commit
b90a522f23167bd00062504803e94220937aba23 making a code path quicker.
Unfortunately initialization was incomplete, as demonstrated by R.E.
Wolff in same review.  Fix is to use GCC designated initializer.
Reference: https://github.com/traviscross/mtr/pull/151
Reference: https://gcc.gnu.org/onlinedocs/gcc/Designated-Inits.html
=> net: fix net_reopen() initialization

mtr.c
By opening the display before the dns process is forked, the child
inherits things like ncurses's handler for SIGWINCH (window resize
event), which can cause it to crash and leave the parent process in
an infinite select() loop, freezing the display.
This fixes #156.
=> Initialize dns process before opening display

display.h
Issue introduced by 2e4369a61c5bf5a6c221a49350e71f8dfebba539, displaymode 2 was missed when converting from ints to an enum.
This fixes #155.
PS: This kind of breakage is not unexpected considering the ridiculous size of the pull request which introduced it... Looks like those commits should be reviewed more thoroughly.
=> Add displaymode 2 back in

gtk.c
This fixes the bug about mtr being almost unusable with dark GTK+ themes. Now non-down rows are colored based on whatever current theme offers instead of `black`.
=> Respect theme foreground color

configure.ac, ui/curses.c, ui/display.c, ui/display.h, ui/mtr.c, ui/split.c
pkg-tool is indeed an elegant way to check for the presence
of libraries.  When using pkg-config to check for ncurses, this
works great... for Linux.  Unfortunately, on FreeBSD and MacOS,
ncurses is installed by default, but pkg-config is not.  When
pkg-config is installed on these systems, it doesn't know about
the system installed ncurses.
Therefore, somewhat counterintuitively, it is better for portability
to just us AC_CHECK_LIB instead of PKG_CHECK_MODULES to find
ncurses.
=> build: use AC_CHECK_LIB for ncurses, rather than pkg-tool

packet/command.c, packet/probe.h, packet/probe_cygwin.c, packet/probe_unix.c, packet/probe_unix.h, test/probe.py, ui/cmdpipe.c
If we fail to open any IPv6 sockets, rather than aborting with an
unrecoverable error, fall back to IPv4 only support.  Socket
creation might fail, for example, when Linux is booted with
the kernel command-line "ipv6.disable=1".
In the case where opening IPv6 sockets fail,
'check-support feature ip-6' will indicate there is no support
for sending IPv6 probes.
Stricter error reporting revealed that test for protocols other
than ICMP were running on Cygwin.  Modified the tests such that
they won't run if the protocol isn't supported.
This fixes the issue reported by @yvs2014 yesterday.
=> mtr-packet: Fall back to IPv4 only support if IPv6 sockets fail to open

Makefile.am, README, configure.ac, packet/cmdparse.c, packet/command.c, packet/construct_unix.c, packet/deconstruct_unix.c, packet/probe.c, packet/probe.h, packet/probe_unix.c, packet/wait_unix.c, portability/queue.h, ui/asn.c, ui/cmdpipe.c, ui/curses.c, ui/display.c, ui/display.h, ui/dns.c, ui/mtr.c, ui/split.c, ui/utils.c
Included are fixes to building and running on Solaris, NetBSD and OpenBSD.  Some are related to linking with curses / ncurses, and some are related to new mtr-packet code.
I have tested that, as of this change, mtr builds, links with ncurses or curses without hassle, and functions on each of:
Cygwin 2.6.0 on Windows 10
Debian 8.6.0  ("Jessie")
Fedora 25
FreeBSD 11.0
MacOS 10.12.2  ("MacOS Sierra")
NetBSD 7.0.2
OpenBSD 6.0
Raspbian 8  ("Jessie" on armv6l)
Solaris 11.3
Ubuntu 16.10
=> Portability fixes - Solaris, NetBSD and OpenBSD

build-aux/mtr.bat, ui/cmdpipe.c
It is not nice to execute program based on some env variable. Also the
workaround for (non)issue make it harder to work with mtr without
installing in my opinion.
First we try mtr-packet from PATH. In case it is not found we try binary
from current directory. This way user can easily overwrite selected
binary by modifying PATH env variable. But we don't require having
either mtr or mtr-packet in PATH.
Also fix batch file to support paths with spaces on Windows.
------------------------------------
I'm open for discussion, but I find current design little bit clunky.
=> Remove unnecessary MTR_PACKET env variable.

packet/command_cygwin.c, packet/probe_cygwin.c
This fixes compilation with Clang on Cygwin.
=> Add missing errno.h include.

ui/report.c
When generating JSON output, and when no hosts are found when
probing, the generated JSON was malformed.  (i.e. when the "hubs" list
in the generated JSON is empty, there was no closing bracket.)  This can
be reproduced by tracing to an unused host address on the local subnet.
This fixues issue #190.
=> json: Fix malformed json when the "hubs" list is empty

packet/deconstruct_unix.c, packet/probe.c, packet/probe_cygwin.c, ui/cmdpipe.c, ui/cmdpipe.h, ui/curses.c, ui/display.c, ui/display.h, ui/net.c, ui/net.h
When a host is reported as unreachable in response to a particular network probe, the Windows version of the mtr UI had the unfortuante behavior of exiting and and printing a terse message.  This is surprising to a user, who would expect mtr probes and reporting to continue.
With this change, probing continues and a status reading "no route to host" is displayed in the probe report.
This change will also improve the reporting of the Unix version of mtr, now specifying "no route to host" instead of misleadingly indicating that no reply has been received.
This fixes issue #179.
=> Report "no route to host" in curses UI when a probe response arrives with an ICMP destination unreachable code

man/mtr.8.in, ui/mtr.c, ui/mtr.h, ui/net.c
Using '--interface' on the commandline (or '-I') will specify
a network interface by name.  This is sometimes a more convenient
alternative to using '--address' for specifying a source address
from which to send probes.
This can be useful when you have both a wired ethernet connection
and WiFi connection, and wish to use a specific connection for the
purposes of tracing.
This feature was requested in issue #207.
This change also cleans up main() slightly by factoring out the
hostent structure generation.
=> commandline: Added --interface for using a named network interface

configure.ac, packet/command.c, packet/construct_unix.c, packet/deconstruct_unix.c, packet/deconstruct_unix.h, packet/probe.c, packet/probe.h, packet/probe_cygwin.c, packet/probe_cygwin.h, packet/probe_unix.c, packet/probe_unix.h, packet/wait_unix.c
This commit enables non-privileged users to use mtr on linux without
setuid. Currently ICMP and UDP protocols are supported in this commit.
Previously, to use mtr on linux with protocol ICMP and UDP, RAW sockets
have to be opened to send out packets and receive ICMP errors, so users
must have RAW socket permission to use this program. The goal of this
commit is to make mtr usable for normal users without RAW socket
permission. A sysctl might need to be set to make this work,
https://lkml.org/lkml/2011/5/18/305
The changes include:
(1) The origianl logic is not changed, but instead, when the program
fails to open RAW sockets, it will fallback to opening DGRAM scoekts.
(2) A new flag is created to indicate whether RAW socket is used for
IPv4 and IPv6 respectively.
(3) When using DGRAM …
=> mtr-packet: use ICMP and UDP without privilege on linux

packet/probe_unix.c
This bug causes mtr not working on IPv6 only machines if invoked by root
user, and it is fixed in this commit.
=> mtr-packet: fix a bug causing IPv6 raw socket not working

man/mtr.8.in
This fixes a very small typo discovered by lintian while i was packaging 0.92 for debian
=> [typo]mtr.8.in: s/allows to/allows one to/

ui/asn.c
```
sudo ./mtr -y 1 baidu.com
```
```
Host                                                          Loss%   Snt   Last   Avg  Best  Wrst StDev
1. bogon                                                       0.0%    10    2.0   2.6   2.0   3.9   0.7
2. 1.80.202.1.static.bjtelecom.net                             0.0%    10    3.3   5.0   3.3  11.2   2.3
3. bj141-158-73.bjtelecom.net                                  0.0%    10    3.0   3.9   2.6   6.0   1.4
4. 220.181.0.54                                               66.7%    10    4.2   4.5   4.2   4.9   0.4
5. (waiting for reply)
6. 220.181.17.94                                               0.0%     9    5.7   4.5   3.2   7.7   1.4
7. (waiting for reply)
8. 220.181.57.216                                              0.0%     9    4.4 …
```
=> Option --ipinfo 1 can not work properly

packet/probe_unix.c
Under Linux Vserver SOCK_RAW is quite limited. Only IPPROTO_ICMP works,
so try to use it.
check_length_order() also doesn't work because sendto is also limited.
Fortunately under linux check_length_order is not needed as described
in comment around check_length_order.
Fixes #223 for me.
=> Also try SOCK_RAW/IPPROTO_ICMP when other fail.

packet/probe.c, ui/net.c
In mtr 0.87 it was possible to start mtr against unreachable
host (that local kernel already knew that it is unreachable).
Later it was broken. Make such tracing possible again.
Fixes #224 for me.
=> mtr to a unreachable host is possible again.

man/mtr.8.in
This adds the UI hotkeys (from the internal help accessed via ? while mtr is running) to a new NOTES section in the mtr man page, for better discoverability.
=> added UI hotkeys to NOTES section in man page

.dir-locals.el, packet/command_unix.c, packet/packet.c, packet/probe.c, packet/probe_unix.c, packet/wait_unix.c
Print the program name (mtr or mtr-packet) in front of error messages so that a user can distinguish better which part an error occured in.
=> Print program name before error messages.

Makefile.am
Change 817f171d broke the MacOS build.
Change 817f171d converted the error reporting in mtr-packet from
perror() to error().  That's fine, but error() is missing on MacOS.
We already had portability/error.c for this reason, but that was
previously only linked into the mtr binary, not mtr-packet.
This change also links portability/error.c with mtr-packet, when
error() is missing from the OS.
=> Link portability/error.c with mtr-packet when missing on MacOS

man/mtr-packet.8.in
There is now a package for Python which invokes mtr-packet and sends
network probes asynchronously:  https://pypi.org/project/mtrpacket/
This change adds mention of it to the mtr-packet man page, which
should help people interested in using mtr-packet in monitoring scripts
find it.
=> Mention Python mtrpacket package in mtr-packet man page

packet/probe_unix.c
Use MIN_PORT to MAX_PORT port range to avoid getting EADDRNOTAVAIL caused by
sockets in FIN-WAIT-1 state.  This issue is easy to reproduce with following
loop (as root).
src="$(ip route | awk '/default/ {print $9}')"
while true; do
echo "6000 send-probe ip-4 1.1.1.1 local-ip-4 $src port 443 protocol tcp" |
./mtr-packet
done | head -n 10
6000 reply ip-4 1.1.1.1 round-trip-time 11306
6000 address-not-available
6000 address-not-available
[...]
Reported-by: Scott Pearson <scott@cloudflare.com>
Reproeuced-by: Jarred Trainor <jarred@cloudflare.com>
Signed-off-by: Sami Kerola <kerolasa@iki.fi> && <kerolasa@cloudflare.com>
=> mtr-packet: make address-not-available errors less likely

Makefile.am, configure.ac, packet/construct_unix.c, packet/construct_unix.h, packet/deconstruct_unix.c, packet/probe.c, packet/probe.h, packet/probe_unix.c, packet/sockaddr.c, packet/sockaddr.h
in certain circumstances -I'm aware of specifying localport and port in udp mode- mtr-packet sends udp packets with invalid checksum.
```
"33000 send-probe ip-4 1.1.1.1 local-ip-4 1.2.3.4 protocol udp size 64 bit-pattern 0 tos 0 ttl 1 timeout 10 port 123 local-port 33333 bit-pattern 111" | sudo ./mtr-packet
```
The changes correct this behaviour, they calculate the udp checksum and write to the required offset.
=> udp checksum is incorrect

ui/net.c
It only tries to get the IP address if there is one.
The interface might be listed more than once, so it still finds the IP address of my tunnel interface I tested on. Else it will fall back to normal error handling.
=> fix segmentation fault if there is no IP address on an interface (fixes #320)

ui/net.c
The `net_send_query` function was use global varible `packetsize` and ignoring `packet_size` parameter.
=> Fix parameter in ui/net.c

ui/curses.c
This is a clean version of #337 without the extra commits and whitespace changes.
This should also fix issue #230 as it appears to be the same.
As mentioned in the issue and previous PR, this feature would be extremely useful when running multiple copies of `mtr` to different destinations.
=> Add display of destination.

Makefile.am, configure.ac, man/mtr.8.in, ui/display.c, ui/display.h, ui/mtr.c, ui/report.c
I reworked JSON report to use libjansson. Consider such solution more robust.
I noticed that fixes JSON output when no hosts:
<details>
<summary>Screenshot with comparison</summary>
</details>
Also, it changes the following:
- report.mtr.{tests, tos} now output as number;
- report.hubs[].count now output as number;
- the precision of real numbers differs;
<details>
<summary>Screenshot with comparison</summary>
</details>
=> report: json: reworked with libjansson

TODO, ui/net.c, ui/report.c
Code Changes : Always store the recent/latest responder at hop-X at nh->addr[0] and all older hosts in nh->addrs[]. This allows maxTTL to change automatically when path-changes.
=> Code to allow maxTTL to change dynamically when path changes in the middle of mtr execution

ui/curses.c, ui/net.c, ui/net.h
This PR is a further extension of #345 
With the consideration of symmetry, since we display the local hostname with its source address, we should also display the remote hostname with its remote address.
This change also adds more information when running multiple `mtr` as #345 intended to do.
To keep the symmetry, codes were added following the original style, namely replicas of `localaddr` and `net_localaddr` were made.
The new static char array `remoteaddr` can be used in other modes like report or gtk. This consideration is for further development. Not to be addressed in this PR.
=> Add display of destination with resolved addr under curses mode

ui/net.c
The provided types are compatible with the function signature.
Moreover, this seems to hide a bug where `display_rawhost()` is called
with an address instead of an MPLS struct.
=> ui: don't cast to void* when calling display_rawhost()

ui/dns.c, ui/dns.h, ui/mtr.c
[edit] was addressing 378
In particular addresses the case where changing from one address family to another. ie when launching mtr with an ipv6 address, then in the gtk interface changing to an ipv4 address.
@robert-scheck I currently cannot test this, are you able to see if it addresses your use case?
=> tell dns process which family we want resolved

ui/curses.c
`ncuses-6.3` added printf-style function attributes and now makes
it easier to catch cases when user input is used in palce of format
string when built with CFLAGS=-Werror=format-security:
ui/curses.c:765:42:
error: format not a string literal and no format arguments [-Werror=format-security]
765 |         mvprintw(rowstat - 1, startstat, msg);
|                                          ^~~
Let's wrap all the missing places with "%s" format.
=> ui/curses: always use "%s"-style format for printf()-style functions

ui/curses.c
Change d2552ca has the side effect of moving hosts around in the
multipath view, as the last host to reply to a packet was set as
addr.  Using addrs[0] istead of addr to draw the first host keeps
the ordering deterministic, in order of first reply.
=> use addrs for static host ordering in curses

man/mtr.8.in, ui/curses.c, ui/mtr.c, ui/mtr.h, ui/report.c
It is not unknown to have datacenters with over 8 ECMP paths between two
hops.  Expand the maximum number of ECMP hosts stored in addrs to 128,
and add a new option to control the number to display, defaulting to the
old MAX_PATHS of 8
=> add --max-display-paths option

packet/command.c, packet/construct_unix.c, packet/probe.h, ui/cmdpipe.c
This is done by traceroute and other tools as well. It requires CAP_NET_RAW, but without it the `-I` option doesn't seem to have any effect.
I could only test with IPv4, but it worked fine for ICMP, TCP and UDP. Not sure if additional handling is required for the case where CAP_NET_RAW isn't available it shows "Unexpected mtr-packet error" like it does for `-M`. Before this change there was no error, but it didn't take the interface into account.
Could be relevant for #379, #250, #232, although it doesn't handle the `-a` option. This is comparable to `traceroute` though. `traceroute -s <IP>`  shows the same (wrong?) hops as `mtr -a <IP>` after this change, while `traceroute -i <NAME>` shows the same (correct) hops as `mtr -I <NAME>`. So I'd argue that this is the correct behavior.
=> Set SO_BINDTODEVICE for `-I`

packet/probe_unix.h
Port 33434 is the IANA-reserved port for traceroute. It also seems to be
the most common start port. The following implementations, and
likely others, use it as their start port:
- Apple macOS traceroute
- FreeBSD traceroute
- GNU inetutils-traceroute
- Modern traceroute for Linux
- OpenBSD traceroute
The benefit to using a standard starting port is that some firewalls may
have these ports allowed, whereas other ports may be blocked, so there
is a greater probability the probe will succeed.
I’m uncertain if the `SEQUENCE_NUM` and `MinSequence` constants should also be changed.
=> Adjust MIN_PORT to match other implementations

ui/mtr.c
Before this change the report gave successful exit value when destination
hostname could not be found.
$ ./mtr --report nxdomain. ; echo $?
./mtr: Failed to resolve host: nxdomain.: Name or service not known
0
Quickly looking 'git grep ---after-context if.*Interactive' there does not
appear to be more than the two instances in main() where exit is called
depending on interactive, so this change should cover all these cases.
Reported-by: Marek Kroemeke <mkroemeke@cloudflare.com>
Signed-off-by: Sami Kerola <kerolasa@iki.fi>
=> ui: make interactive and non-interactive exit code the same

ui/report.c
basically changed
-        snprintf(buf + len, sizeof(buf), fmt, data_fields[j].title);
+        snprintf(buf + len, sizeof(buf) - len, fmt, data_fields[j].title);
is spotted by FORTIFY_SOURCE
=> fixed the sizes passed into snprintf

configure.ac
Since 9eddfacd8e9b9c2f4ce6f7ef98814bff02b5a2b7 the binding to libcap and dropping of capabilities has been silently broken.
As the docs for `AC_CHECK_LIB` are written 
> If action-if-found is not specified, the default action prepends -llibrary to LIBS and defines ‘HAVE_LIBlibrary’ (in all capitals).
After said commit, action-if-found _was_ specified, and thus `HAVE_LIBCAP` wasn't defined anymore, nor was `-lcap` added to the LIBS variable.
This PR fixes this by inverting the `$have_cap` definition
=> configure.ac: fix broken cap check

.flake8, .github/workflows/test.yaml, .gitignore, configure.ac, test/probe.py
In the test folder, there was lint.sh, but I think flake8 is a better tool. When this PR is reviewed, let's discuss if we can use flake8  in which case I can remove lint.sh.
Added a compile job for linux, this runs compilation as defined in the README, runs a sample mtr to 1.1.1.1 and runs cmdparse.py test. Need documentation on what other tests to run and whether to include the testing in tox instead of running them individually.
Not adding in this PR support for cygwin, macos, or freebsd, as that will need investigation on how to run.
Minor:
- Fixed a typo in configure.ac that used 4 dashes vs 2 for a flag option.
Actions will run when this gets merged in.
The actions ran in my fork from this commit: [MTR github actions run](https://github.com/darless/mtr/actions/runs/5523401612)
Items …
=> Github actions added to perform lint and compile

packet/construct_unix.c, packet/packet.c, packet/utils.h
This PR addresses issues related to capability handling in `mtr-packet`, as detailed in issue #485. It completely resolves Bug 1 and partially resolves Bug 2 by ensuring that `CAP_NET_RAW` and `CAP_NET_ADMIN` are retained in the permitted set. These capabilities are elevated to the effective set when necessary. This eliminates "permission denied" errors encountered when specifying a local interface using the `--interface` flag or setting a packet mark with the `-M` option. To the best of my knowledge, these issues are specific to Linux.
The commits have been tested on Linux version 6.1.51.
=> Adjust capability handling

README.md
It would be much simpler and not experience IPv6 related build fail at all.
Note: will give popup window to show progress.
=> Add WSL method to Windows Install

packet/probe_cygwin.c, packet/probe_cygwin.h
Recent versions of Cygwin implement pipe() using Windows' named pipes, and put the read end of the pipe in FILE_PIPE_COMPLETE_OPERATION mode, which doesn't allow overlapped I/O operations.
For the relevant commit in the Cygwin repository, see 9e4d308cd592fe383dec58ea6523c1b436888ef8
Happily, this mode is approximately equivalent to Unix's non-blocking read mode, so we can avoid overlapped I/O entirely, and instead wait on the Windows handle for the read end of the pipe when we need an alertable wait to receive ICMP probe completions.
Thanks to Adam Schultz for research into this issue and a first attempt at a fix.
This fixes issue #465
=> Update Cygwin ICMP service thread for asynchronous pipes

ui/curses.c, ui/display.h, ui/mtr.h, ui/select.c
Saves 5 lines of screen space in curses when 'c' is pressed.
=> Add a compact mode in curses

man/mtr-packet.8.in, packet/probe.c, packet/probe_unix.c, ui/cmdpipe.c, ui/display.c
Handle EHOSTDOWN which occurs on MacOS and causes:
% mtr 192.168.68.2
mtr: Unexpected mtr-packet error
for unreachable host and also split error handling better granularity.
=> Handle EHOSTDOWN and refine error handling better granularity

ui/utils.c
As @yvs2014 noted in https://github.com/traviscross/mtr/issues/523#issuecomment-2660970185, it is unnecessary to check whether an int is larger than the maximum int value. An int cannot be greater than the maximum int value.
Follows https://github.com/traviscross/mtr/pull/525
=> Remove redundant code

ui/curses.c, ui/mtr.c, ui/net.c
With an input of `-28` the expression `(-ctl->cpacketsize - MINPACKET)` became 0, which triggered a zero division. This error is fixed by introducing a check to see if there is any room for randomness. Furthermore, a check of the input arguments in the command line and in curses is performed.
MINPACKET assumes IPv4, so these checks do not apply to IPv6. mtr still seems to work with IPv6, so it is likely that there is an additional check elsewhere.
I think it's still okay to assume IPv4 for MINPACKET (the minimum size of a packet), since IPv4 packets are smaller than IPv6 packets (due to the IP header).
=> Fix https://github.com/traviscross/mtr/issues/475

configure.ac, ui/curses.c, ui/display.h, ui/mtr.h
This PR adds support for `--displaymode 3` which renders a graph using unicode braille characters.
Changes include:
* modify autoconf to detect `libncursesw` for wide char support
* only build `WITH_BRAILLE_DISPLAY` when wide support is detected
* since braille chars can show 2x the information, increases `SAVED_PINGS` to 400
* added `DisplayModeBraille` which allows setting `--displaymode 3`
* all rendering changes are in `ui/curses.c`
* with `DisplayModeBraille` selected, `mtr_curses_graph` will call `mtr_fill_graph_braille` instead of `mtr_fill_graph`
* braille characters can render 4 levels of dots, but I found that I could only use 3 to avoid lines bleeding into one another, while the bottom row becomes the origin line
* for each host, the values collected are scaled to fit the 3 …
=> mtr braille graph support

ui/mtr.c, ui/report.c
I think it is a good idea to set the encoding of XML documents to UTF-8, so that a consistent result can be achieved on every platform. Furthermore, the document (can) exists without an external DTD.
=> Set UTF-8 encoding for XML reports

ui/split.c
Split mode only prints lines that have changed, so initializing them to "???" means that unknown / hidden hops are never printed.
Fixes https://github.com/traviscross/mtr/issues/108
=> Initialize lines to empty string in split mode

ui/net.c
When mtr is compiled with IPv6 enabled, the GTK frontend sets the address family to AF_UNSPEC when changing destinations. However, addrcomp does not support this AF type, which causes all comparisons to not match. For the GTK frontend, this leads to a cascading failure when setting the destination to a host that does not resolve:
1. Upon setting `ctl->af = AF_UNSPEC`, `net_max()` will report that all hops have data, as no hops can match the previous remote address.
2. The GTK frontend tries to render a row for every hop, including its IP / hostname.
3. The guard in the GTK frontend to avoid looking up unknown addresses also fails, causing mtr to flood DNS packets and effectively hang.
Fixes https://github.com/traviscross/mtr/issues/533
=> net: implement addrcmp for AF_UNSPEC

packet/construct_unix.c, ui/asn.c
Only try to set IPv6 ToS if the system's IPv6 stack supports RFC 3542 (IPV6_TCLASS)
Skip trying to set BIND_8_COMPAT on Darwin, since on ancient versions it breaks the build due to conflicts and an on more recent versions it either includes arpa/nameser_compat.h or on current versions, it's a no-op. - Resolves #12
While here, drop an unused variable.
Tested on OS X 10.4 to 10.6, and 10.10.
=> Legacy system build fix

ui/net.c
- By default, each cycle should last 1 second, meaning the interval between two subsequent probes should be "1 sec\numhosts." The numhosts calculation started from the first hop, but if the fstTTL option is specified, it should start from the fstTTL value. This bug led to very frequent probes. Fixed.
- Target achievement conditions should respect the value of the -D (--due-ttl) option if enabled and only trigger after the specified TTL value is reached. Fixed.
=> fix numhosts calculation. Improve -D (--due-ttl) option
