net.c

Specifying a psize for an IPv6 host generates packets that are bigger than they should be. This corrects psize to be consistent with IPv4.  Applies to both master and newdns branches.

Correct psize bug for IPv6.

---

mtr.c
net.c

Add SCTP support

---

mtr.8

I noticed that users don't get to read about some of the features of mtr, so I thought I'd help out. I have filled in some of the man page sections previously marked as MISSING.

Filled in some of the missing man page sections.

---

README

As you requested, I've updated the README to state that bugs should be submitted to the Github bug tracking system.

State that Github is the preferred way to report bugs.

---

mtr.8
mtr.c
net.c

I broke this out as separate pieces, but they're all mostly related.

allow udp traceroute with fixed source and destination ports

---

mtr.c

Align everything nicely, update helpful comments, and use NULL instead
of 0 for the third element of long_options: it's a pointer, see getopt(3).

Cosmetic cleanup of the option-parsing code

---

asn.c
mtr.8
select.c

This feature was a bit broken, probably because it was not documented (and so nobody used it).  Fix and document.

Improve ipinfo

---

asn.c
display.c
gtk.c
mtr.8
mtr.c
net.c
select.c

This merges the recent updates (IP info and ASN lookups in GTK interface) from the master branch into the newdns branch.

Sync up recent master updates into newdns

---

gtk.c

Avg and Best were swapped in the GTK display.
Update my email address in the GTK credits.

Fix GTK display order.  Update an email address in the GTK credits display.

---

mtr.8
mtr.c
select.c

useful when running a single probe on a network where many hops never respond

add option to set graceperiod

---

asn.c
curses.c
dns.c
dns.h
gtk.c
hello.c
mtr.c
net.c
report.c
select.c

This pull request is mostly about making usage output useful. Earlier printout of short options without explanation did not give enough context to understand what the options might do without looking to manual page, and that renders the help output useless. The new output is hopefully much more helpful, altough it requires more maintenance care.
Rest of the changes are clean ups of various sorts.

new usage() and few cleanups

---

Makefile.am
configure.ac
curses.c
display.c
gtk.c
img/Makefile.am
mtr.8
net.c
report.c

The second pull request is mostly about fixing all the remaining warnings I could find with clang, gcc, and cppcheck. Now when the build is clean I can start focusing to bulid-sys change set. For example 'make distcheck' does not work, but that shall be addressed in the next pull.
p.s. I normally have worked with project using maillist for change reviews, so please be patient while I try to get up to speed with github interface.

Warnings branch

---

configure.ac
curses.c
dns.c
net.c
report.c

Sorry about bit of a mess with autotools revamp. Here are fixes to mine and others regressions. In same go some warnings got to be removed.

2016 08 17 regression fixes and warnings removal

---

net.c

Fix standard deviation calculation.

---

mtr.8.in

Found +. -. Ctrl-L keys and described their function under the --curses option.
Maybe also add these keys to the output of the onscreen help?

Mention + and - keys in the man page

---

configure.ac
dns.c
mtr.c
mtr.h
net.c

This should be straightforward to review.  Commit messages has further detail what is done and why.

2016-09-29 BSD build fix and minor improvements

---

asn.c
configure.ac
curses.c
display.c
dns.c
dns.h
gtk.c
mtr.c
mtr.h
net.c
net.h
raw.c
report.c
select.c

This pull request is full of cleanups and clarifications, some compiler warning fixes, and few option parsing fixes that I revisited thanks to Narthorn. Quite honestly I think next thing I should do is to stop sending pull request until a next release is out. Assuming of course bugs are not reported, leading to need to fix stuff that I have potentially broken.

2016-10-11 let the dust settle

---

mtr.c

Change 1ed2bab broke multiple host names, either specified through
the --filename option, or listed on the commandline.  This was
due to well-intentioned refactoring of the hostname linked list
management which happened to lose all host names other than the
last name in the list.
I've fixed the append_to_names to walk the list of host names before
appending a new host name.  This does make the building of host names
O(n^2) rather than O(n), but I'm skeptical that will impact anyone's
life in a negative way, because it only happens at startup, and
it does simplify the code.
Also, multiple host names will now work in all non-interactive modes
(i.e. report, txt, json, xml, raw, csv) instead of just CSV mode.

cmdline: multiple host names dropped all but one host  (issue #168)

---

mtr.8.in
mtr.c

Make all compile time conditional options to behave same way, and add --sctp to manual page.

2016-10-29 usage improvements

---

.gitignore
COPYING
packet/cmdparse.c
packet/cmdparse.h
ui/asn.c
ui/curses.c
ui/display.c
ui/dns.c
ui/gtk.c
ui/mtr.c
ui/net.c
ui/raw.c
ui/report.c
ui/select.c
ui/split.c
ui/utils.c

All pretty trivial. Should be pretty straightforward to review.

couple maintenance changes

---

packet/probe_cygwin.c

When IcmpParseReplies returned with a probe completion, but the
probe's status was IP_DEST_HOST_UNREACHABLE, mtr-packet was failing
to report the probe result, and was instead printing an unhelpful
error message without any reference to a particular probe.  Now
it will report a "no-route" result with the token associated with
the probe.
This fixes issue #179.

mtr-packet: Report probe status on host unreachable (Cygwin)

---

ui/net.h

include <sys/select.h> for fd_set

---

ui/report.c

Add AS number to json output when passing the correspondent ipinfo parameter

Add AS number to json output

---

ui/asn.c

sudo ./mtr -y 2 qq.com
``` 
Host                                                  Loss%   Snt   Last   Avg  Best  Wrst StDev
1. AS???    bogon                                      0.0%     7    4.2   4.1   3.0   5.8   0.9
2. AS4847   1.80.202.1.static.bjtelecom.net            0.0%     7    5.3   5.2   3.7   8.0   1.4
3. AS4847   229.252.120.106.static.bjtelecom.net       0.0%     7    3.6   4.4   2.7   6.4   1.2
4. AS4847   162.253.120.106.static.bjtelecom.net       0.0%     7    4.8   4.9   4.1   6.4   0.7
5. AS???    202.97.65.62                              42.9%     7   38.2  37.9  37.4  38.3   0.4
6. AS4816   119.147.223.122                            0.0%     7   36.3  38.6  35.7  44.8   3.0
7. (waiting for reply)                                
8. AS4816   14.17.2.122 …
```

Option --ipinfo n can not work properly

---

README

use setup.exe's package manager mode, replacing apt-cyg

---

ui/curses.c

Signed-off-by: Adrien Gallouët <adrien@gallouet.fr>

Add a help line for the t command in curses

---

Makefile.am
ui/curses.c
ui/dns.c
ui/gtk.c
ui/net.c
ui/net.h
ui/split.c

remove redundant functions and try to simplify/improve readbility

sockaddr related cleanups

---

packet/probe_unix.c

only set the remote port in raw packet, not as sendto parameter
does not fix local and remote port, seq number is checksum then,
payload has to be adjusted as with ipv4
fixes #328

ip6 udp - fix probes with local or remote port

---

README.md
man/mtr-packet.8.in
man/mtr.8.in

few updates to manual page and README.md

few updates to manual page and README.md

---

packet/cmdparse.c
packet/construct_unix.c
packet/probe.h
packet/probe_cygwin.c
packet/probe_unix.c
packet/probe_unix.h
packet/wait_unix.c
test/packet_listen.c
test/param.py
test/probe.py
ui/cmdpipe.c
ui/dns.c
ui/net.c

Minor edit: Updating code comments in multiple files

Updating some comments

---

ui/report.c

looks good. Multiple servers in reports.

Added code to print multiple addresses regitered on the same hop count

---

ui/gtk.c
ui/net.c

Fixes https://github.com/traviscross/mtr/issues/378
I moved the "starting a new traceroute" part of `net_reopen` to it single caller in `gtk.c`
Then moved the common parts of `net_open` to `net_reopen` including the initialisation of the source addresses, and now call `net_reopen` from `net_open`

Fix changing source

---

ui/curses.c
ui/dns.c
ui/dns.h
ui/gtk.c
ui/mtr.c
ui/net.c
ui/raw.c
ui/report.c
ui/split.c

fixes https://github.com/traviscross/mtr/issues/378
This should be a set of fairly non controversial changes
With this PR you can start off with `mtr <ip_v6_addr>`, then in the gtk interface, change to a ip v4 address.
Two other issues have been identified in the discussion of https://github.com/traviscross/mtr/pull/394, and I'd like to raise and discuss those separately, and this PR would be a prerequisite for addressing them.

Reset address family

---

test/probe.py
ui/dns.c
ui/dns.h
ui/gtk.c
ui/mtr.c
ui/mtr.h
ui/net.c
ui/net.h

use `getaddrinfo` for both TUI and GUI
fixes https://github.com/traviscross/mtr/issues/398

Consistent resolution strategy

---

ui/mtr.c

addresses #358 
addresses #377

dont show json option if not available

---

ui/report.c

Re-used most of the logic already defined in report_close.
Might be worthwhile to add another option? Currently, so long as --csv comes after --report-wide, the following will print:
```
./mtr ft.com -4 -T -n --report-cycles 5 --report-wide --csv
Mtr_Version,Start_Time,Status,Host,Hop,Ip,Loss%,Snt, ,Last,Avg,Best,Wrst,StDev,
MTR.0.94,1639463558,OK,ft.com,1,???,0.00,5,0,0.70,0.98,0.70,1.75,0.45
MTR.0.94,1639463558,OK,ft.com,2,???,0.00,5,0,9.82,10.60,9.45,12.03,1.06
MTR.0.94,1639463558,OK,ft.com,3,???,100.00,5,5,0.00,0.00,0.00,0.00,0.00
MTR.0.94,1639463558,OK,ft.com,4,72.129.2.22,0.00,5,0,30.57,30.80,10.70,78.62,27.69
MTR.0.94,1639463558,OK,ft.com,5,72.129.1.0,0.00,5,0,13.30,14.65,13.30,18.19,2.05
MTR.0.94,1639463558,OK,ft.com,6,66.109.6.92,0.00,5,0,18.66,16.32,12.97,18.66,2.49 …
```

Report secondary servers when CSV + wide report is enabled

---

ui/mtr.c

```
`-E --max-display-path` is a helpful feature in  ECMP network environment.
Add the help info for this option
```

Add help info for option -E

---

man/mtr.8.in
ui/asn.c
ui/mtr.c
ui/mtr.h

This should fix #238 and related issues.

Add option to use custom ipinfo provider

---

ui/asn.c

Before, addresses in [`64:ff9b::/96`](https://en.wikipedia.org/wiki/NAT64) would all show their ASN as `???`.
This PR looks up what ASN the corresponding IPv4 address belongs to, and displays that instead.

Implement ASN lookups in well-known nat64 prefix

---

ui/report.c

Closes https://github.com/traviscross/mtr/pull/524
Fix https://github.com/traviscross/mtr/issues/522

xml report: remove leading spaces
